/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rquota.h"
#include <strings.h> /* for bzero() */

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

getquota_rslt *
rquotaproc_getquota_1(getquota_args *argp, CLIENT *clnt)
{
	static getquota_rslt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RQUOTAPROC_GETQUOTA,
		(xdrproc_t) xdr_getquota_args, (caddr_t) argp,
		(xdrproc_t) xdr_getquota_rslt, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

getquota_rslt *
rquotaproc_getactivequota_1(getquota_args *argp, CLIENT *clnt)
{
	static getquota_rslt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RQUOTAPROC_GETACTIVEQUOTA,
		(xdrproc_t) xdr_getquota_args, (caddr_t) argp,
		(xdrproc_t) xdr_getquota_rslt, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
